version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: init-deploy-aws
    container_name: init-deploy-aws
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["npm", "run", "start:${NODE_ENV}"]