version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: init-deploy-aws
    container_name: init-deploy-aws
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: ["npm", "run", "start:${NODE_ENV}"]

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
