name: develop
run-name: Deploy backend e-website on ${{ inputs.branch }}
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: develop
jobs:
  build:
    runs-on: self-hosted
