name: deploy

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code từ nhánh được chọn
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build Docker image với tag latest
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/init_deploy:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/init_deploy:latest

      # Deploy lên EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/init_deploy:latest
            docker stop init_deploy || true
            docker rm init_deploy || true
            docker run -d --name init_deploy -p 3000:3000 --env-file .env.api ${{ secrets.DOCKER_HUB_USERNAME }}/init_deploy:latest
