name: develop
run-name: Deploy ${{ inputs.platform }} on ${{ inputs.branch }}
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Bạn muốn deploy môi trường nào?'
        required: true
        type: choice
        options:
          - develop
          - staging
      branch:
        description: 'Branch để deploy'
        required: true
        default: develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the selected branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      # Set up Docker to build the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ inputs.branch }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ inputs.branch }}

      # Deploy to EC2 instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ inputs.branch }}
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ inputs.branch }}
